### ISSUE TITLE
Ibt is not working on OSX

### ISSUE THREAD

**Issue by joerghall** [rcook/ibt#10]
ibt shell

Traceback (most recent call last):
  File "/usr/local/bin/ibt", line 11, in <module>
    sys.exit(_main())
  File "/usr/local/lib/python2.7/site-packages/ibt/__main__.py", line 73, in _main
    ctx = Context(working_dir)
  File "/usr/local/lib/python2.7/site-packages/ibt/context.py", line 17, in __init__
    self._user_info = get_user_info(working_dir)
  File "/usr/local/lib/python2.7/site-packages/ibt/util.py", line 125, in get_user_info
    return map(_sanitize, check_process(["stat", "-c", "%u:%G:%g:%U", working_dir]).strip().split(":"))
  File "/usr/local/lib/python2.7/site-packages/ibt/util.py", line 68, in check_process
    raise RuntimeError("Popen command failed: {}".format(error))
RuntimeError: Popen command failed: stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]

**Comment by rcook** [comment]
macOS's stat command doesn't support the `-c` option, so this command is failing: `stat -c %u:%G:%g:%U .`. Need to find the macOS equivalent of this.

**Comment by rcook** [comment]
Pushed ibt-0.4 with this fix.

**Comment by rcook** [comment]
Published version 0.6 which should (hopefully) fix the various packaging problems.
