### ISSUE TITLE
Unable to install ibt with pip

### ISSUE THREAD

**Issue by joerghall** [rcook/ibt#8]
pip install --user ibt

Collecting ibt
  Using cached https://files.pythonhosted.org/packages/6e/08/4b3296c50f5b7e83e9e96d5e2ae5996ddffa6e3e15d259875aa167149a97/ibt-0.2.tar.gz
    Complete output from command python setup.py egg_info:
    
    Installed /private/var/folders/8s/s7rfrprd05s87_02v5r69z5d374z1v/T/pip-install-xOqvaQ/ibt/.eggs/setuptools_markdown-0.2-py2.7.egg
    Searching for pypandoc
    Reading https://pypi.python.org/simple/pypandoc/
    Downloading https://files.pythonhosted.org/packages/71/81/00184643e5a10a456b4118fc12c96780823adb8ed974eb2289f29703b29b/pypandoc-1.4.tar.gz#sha256=e914e6d5f84a76764887e4d909b09d63308725f0cbb5293872c2c92f07c11a5b
    Best match: pypandoc 1.4
    Processing pypandoc-1.4.tar.gz
    Writing /var/folders/8s/s7rfrprd05s87_02v5r69z5d374z1v/T/easy_install-FGSgSx/pypandoc-1.4/setup.cfg
    Running pypandoc-1.4/setup.py -q bdist_egg --dist-dir /var/folders/8s/s7rfrprd05s87_02v5r69z5d374z1v/T/easy_install-FGSgSx/pypandoc-1.4/egg-dist-tmp-jXA6D5
    Maybe try:
    
        brew install pandoc
    See http://johnmacfarlane.net/pandoc/installing.html
    for installation options
    ---------------------------------------------------------------
    
    zip_safe flag not set; analyzing archive contents...
    pypandoc.__init__: module references __file__
    
    
    !!! pandoc not found, long_description is bad, don't upload this to PyPI !!!
    
    
    creating /private/var/folders/8s/s7rfrprd05s87_02v5r69z5d374z1v/T/pip-install-xOqvaQ/ibt/.eggs/pypandoc-1.4-py2.7.egg
    Extracting pypandoc-1.4-py2.7.egg to /private/var/folders/8s/s7rfrprd05s87_02v5r69z5d374z1v/T/pip-install-xOqvaQ/ibt/.eggs
    
    Installed /private/var/folders/8s/s7rfrprd05s87_02v5r69z5d374z1v/T/pip-install-xOqvaQ/ibt/.eggs/pypandoc-1.4-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8s/s7rfrprd05s87_02v5r69z5d374z1v/T/pip-install-xOqvaQ/ibt/setup.py", line 63, in <module>
        zip_safe=False)
      File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 338, in __init__
        _Distribution.__init__(self, attrs)
      File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/local/lib/python2.7/site-packages/setuptools/dist.py", line 471, in finalize_options
        ep.load()(self, ep.name, value)
      File "/private/var/folders/8s/s7rfrprd05s87_02v5r69z5d374z1v/T/pip-install-xOqvaQ/ibt/.eggs/setuptools_markdown-0.2-py2.7.egg/setuptools_markdown.py", line 22, in long_description_markdown_filename
        output = pypandoc.convert(markdown_filename, 'rst')
      File "/private/var/folders/8s/s7rfrprd05s87_02v5r69z5d374z1v/T/pip-install-xOqvaQ/ibt/.eggs/pypandoc-1.4-py2.7.egg/pypandoc/__init__.py", line 66, in convert
        raise RuntimeError("Format missing, but need one (identified source as text as no "
    RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/8s/s7rfrprd05s87_02v5r69z5d374z1v/T/pip-install-xOqvaQ/ibt/

**Comment by rcook** [comment]
This is a strange one. ibt does not have a dependency on Pandoc. This looks a little bit like https://github.com/enigmampc/catalyst/issues/263.

**Comment by rcook** [comment]
This is certainly a strange regression since ibt 0.1 installs just fine.

**Comment by rcook** [comment]
A-ha. I think it's because `README.md` is missing from the package.

**Comment by rcook** [comment]
I've published ibt-0.3 which includes this fix.
